### PR TITLE
Working with new api live stream

### PR DESCRIPTION
**Pull request by alekslyse**
As synology want, this replace the old method and uses the new api with the rtsp stream.

I got a synology home assistant component ready to use this ready

### CODE REVIEW

**Comment by joshtbernstein** [comment]
@alekslyse @snjoetw Would we be able to get this merged in? We'd love to be able to use RTSP in Home Assistant which I believe depends on this.

**Comment by pergolafabio** [comment]
What would be the difference? I am already using the generic component with rtsp stream url...

Will the end result be the same?

The only thing I am not able to, is using the stream: component... It gives me a huge lag...

Will it be better then?

**Comment by joshtbernstein** [comment]
I didn't have good results with the generic component and hoping this would be better. But also you get status and more control over the cameras and synology surveillance station.

**Comment by pergolafabio** [comment]
Indeed, Synology component would be better, for motion detection...
But generic and rtsp stream works the best for me

**Pull request closed without merging**
